name: Sync uat -> prod

on:
  push:
    branches:
      - 'uat'

jobs:
  uat-to-prod-merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat'
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          # Extract branch name from GITHUB_REF
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = ${{ ENV_NAME }}"

      - name: Merge uat -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: uat
          target_branch: prod
          github_token: ${{ secrets.LUQMAN_GA_TOKEN }}

      - name: Print success message
        run: echo "Success!!! UAT is now in PROD"