## This workflow combines all the branches' actions into one yaml file
## and is fully automated from start to the end

name: Feature Branch to Prod Automatic

on:
  push:
    branches:
      - 'dev'
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'

jobs:
  env-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

  dev-to-uat-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> uat
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: uat
          github_token: ${{ secrets.LUQMAN_GA_TOKEN }}

      - name: Print success message
        run: echo "Success!!! DEV is now in UAT"

  uat-to-prod-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

      - name: Merge uat -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: uat
          target_branch: prod
          github_token: ${{ secrets.LUQMAN_GA_TOKEN }}

      - name: Print success message
        run: echo "Success!!! UAT is now in PROD"

  prod-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

      - name: Print success message
        run: echo "Success!!! PROD is good!"